export const STRINGS = {
  zh: {
    appName: 'ace-aws',
    appTagline: 'AWS 认证刷题',
    greeting: '上午好，云端学徒',
    settingsTitle: '设置',
    selectCertTitle: '选择认证',
    selectCertSubtitle: '选择你正在备考的 AWS 认证',
    selectCertCta: '开始练习',
    selectCertSaveFailed: '无法保存选择，请重试。',
    questionListTitle: '题目列表',

    certDvaEyebrow: 'DVA-C02 · 助理级',
    certDvaTitle: '开发人员',
    certDvaQCount: '557 题 · 热门',
    certDvaSelectTitle: '开发人员',
    certClfTitle: '云从业者',
    certAifTitle: 'AI 从业者',
    certSaaTitle: '解决方案架构师',
    certSoaTitle: 'SysOps 管理员',
    certDeaTitle: '数据工程师',
    certMlaTitle: '机器学习工程师',
    certSapTitle: '解决方案架构师',
    certDopTitle: 'DevOps 工程师',
    certAnsTitle: '高级网络',
    certScsTitle: '安全',
    certMlsTitle: '机器学习',
    certGroupFoundational: '基础级',
    certGroupAssociate: '助理级',
    certGroupProfessional: '专家级',
    certGroupSpecialty: '专项',
    certQuestions: '{count} 题',
    certComingSoon: '即将上线',
    certHot: 'HOT',
    certSwitchChip: '切换',
    certSwitchAria: '切换认证',
    certSwitchTitle: '切换认证',
    certSwitchSubtitle: '进度按认证分别保存',
    certSwitchCurrent: '当前认证',
    certSwitchAvailable: '可切换',
    certSwitchComingSoon: '即将开放',
    certSwitchBrowseAll: '查看全部认证',
    selectCertBrowseTitle: '全部认证',
    selectCertBrowseSubtitle: '查看全部 AWS 认证。CLF-C02 与 DVA-C02 题库已就绪。',
    selectCertBrowseCta: '继续当前认证',

    homeContinue: '继续刷题',
    homeAnswered: '已答题',
    homeAccuracy: '正确率',
    homeWrong: '错题',
    homeBookmarks: '收藏',
    homeQuickStart: '快速开始',

    questionXofY: '第 {x} 题 / 共 {y} 题',
    badgeSingle: '单选',
    badgeMulti: '多选 · {n}',
    topicDeployment: '部署',
    topicDevelopment: '开发',
    topicSecurity: '安全',
    topicTroubleshooting: '故障排除',
    topicBillingPricingSupport: '账单、定价与支持',
    topicCloudConcepts: '云概念',
    topicCloudTechnologyServices: '云技术与服务',
    topicSecurityCompliance: '安全与合规',
    practiceCountPrefix: '第',
    practiceCountMiddle: '题 / 共',
    practiceCountSuffix: '题',
    selectN: '还需选择 {n} 项',
    selectedNofN: '已选 {n}/{total}',
    enToggle: 'EN',
    englishOriginal: '英文原文',
    close: '关闭',
    back: '返回',
    notifications: '通知',
    bookmark: '收藏',
    loading: '加载中',

    submit: '提交',
    skip: '跳过',
    next: '下一题',
    retryAnswer: '重新作答',

    bannerCorrect: '回答正确',
    bannerWrong: '回答错误',
    bannerPartial: '部分正确',
    correctAnswerIs: '正确答案是',
    yourAnswer: '你的回答',
    explanationTitle: '解析',
    explanationTag: 'AI · Markdown',
    voteTitle: '社区投票分布',
    voteTitleMulti: '社区作答组合',
    voteOptionCount: '{count} 项',
    voteComboCount: '{count} 种',
    voteOther: '其他',
    voteCorrect: '正确',
    voteYou: '你',
    voteNotInDistribution: '未在投票中',

    tabWrong: '错题',
    tabBookmarks: '收藏',
    tabHome: '首页',
    tabSettings: '设置',

    settingsAppearance: '外观',
    settingsAccount: '账号',
    accountSignedOutTitle: '使用 GitHub 登录',
    accountSignedOutDescription: '登录后会切换到账号本地进度；当前匿名进度暂不会自动导入。',
    accountLocalProgressNotice: '匿名进度仍保存在本机，后续同步阶段会提供导入。',
    signInWithGitHub: '使用 GitHub 登录',
    accountSignedIn: '已登录',
    accountGitHubUser: 'GitHub 账号',
    accountSyncStatus: '同步状态',
    accountSyncCurrentCert: '认证选择已同步',
    accountSyncCurrentCertDescription: '当前认证会跟随这个 GitHub 账号。',
    signOut: '退出登录',
    signOutClearsProgress: '退出会清除当前账号本地进度镜像。',
    loginWelcome: '欢迎回来',
    loginSubtitle: '登录后同步进度到所有设备',
    loginOr: '或',
    continueAsGuest: '以游客身份继续',
    guestModeNotice: '游客模式：进度仅保存在本机',
    loginAuthError: 'GitHub 登录未完成，请重试或以游客身份继续。',
    loginOnboardingError: '无法保存选择，请重试。',
    loginAccountPreferencesError: '无法加载账号偏好，请重试。',
    loginLanguageToggle: '切换语言',
    settingsTheme: '主题',
    themeLight: '浅色',
    themeDark: '深色',
    themeSystem: '跟随系统',
    settingsLanguage: '语言',
    settingsLanguageLabel: '界面语言',
    langZh: '中文',
    langEn: 'English',
    settingsAbout: '关于',
    settingsVersion: '版本',
    settingsPrivacy: '隐私',
    settingsLicense: '开源协议',

    emptyWrong: '暂无错题，继续努力 ✨',
    wrongCountBadge: '错 {count} 次',
    emptyBookmarks: '还没收藏任何题目，去练习中标记吧',
    emptyAllAnswered: '已全部答完 ✨',
    emptyAllAnsweredCta: '去看错题',
    questionNotFound: '题目不存在',

    backToHome: '返回首页',
    viewLastResult: '查看上次结果',
    practiceCompleteTitle: '练习完成',
    practiceCompleteDescription: '该认证已没有未作答题目。',
    wrongReviewCompleteTitle: '错题复习完成',
    wrongReviewCompleteDescription: '本轮错题已全部复习完成。',
    bookmarksReviewCompleteTitle: '收藏复习完成',
    bookmarksReviewCompleteDescription: '本轮收藏题目已全部复习完成。',
    backToWrongList: '返回错题列表',
    backToBookmarks: '返回收藏',
    loadFailed: '加载失败',
    retry: '重试',
  },
  en: {
    appName: 'ace-aws',
    appTagline: 'AWS certification practice',
    greeting: 'Good morning, CloudLearner',
    settingsTitle: 'Settings',
    selectCertTitle: 'Choose certification',
    selectCertSubtitle: 'Pick the AWS exam you are preparing for',
    selectCertCta: 'Start practicing',
    selectCertSaveFailed: 'Could not save your selection. Try again.',
    questionListTitle: 'Question list',

    certDvaEyebrow: 'DVA-C02 · Associate',
    certDvaTitle: 'Developer Associate',
    certDvaQCount: '557 Q · HOT',
    certDvaSelectTitle: 'Developer',
    certClfTitle: 'Cloud Practitioner',
    certAifTitle: 'AI Practitioner',
    certSaaTitle: 'Solutions Architect',
    certSoaTitle: 'SysOps Administrator',
    certDeaTitle: 'Data Engineer',
    certMlaTitle: 'Machine Learning',
    certSapTitle: 'Solutions Architect',
    certDopTitle: 'DevOps Engineer',
    certAnsTitle: 'Advanced Networking',
    certScsTitle: 'Security',
    certMlsTitle: 'Machine Learning',
    certGroupFoundational: 'Foundational',
    certGroupAssociate: 'Associate',
    certGroupProfessional: 'Professional',
    certGroupSpecialty: 'Specialty',
    certQuestions: '{count} questions',
    certComingSoon: 'Coming soon',
    certHot: 'HOT',
    certSwitchChip: 'Switch',
    certSwitchAria: 'Switch certification',
    certSwitchTitle: 'Switch certification',
    certSwitchSubtitle: 'Progress is tracked per certification',
    certSwitchCurrent: 'Current',
    certSwitchAvailable: 'Available',
    certSwitchComingSoon: 'Coming soon',
    certSwitchBrowseAll: 'Browse all certifications',
    selectCertBrowseTitle: 'All certifications',
    selectCertBrowseSubtitle:
      'Browse every AWS certification. CLF-C02 and DVA-C02 banks are ready right now.',
    selectCertBrowseCta: 'Continue current certification',

    homeContinue: 'Continue',
    homeAnswered: 'Answered',
    homeAccuracy: 'Accuracy',
    homeWrong: 'Wrong',
    homeBookmarks: 'Bookmarks',
    homeQuickStart: 'Quick start',

    questionXofY: 'Question {x} of {y}',
    badgeSingle: 'Single',
    badgeMulti: 'Multi · {n}',
    topicDeployment: 'Deployment',
    topicDevelopment: 'Development',
    topicSecurity: 'Security',
    topicTroubleshooting: 'Troubleshooting',
    topicBillingPricingSupport: 'Billing, Pricing, and Support',
    topicCloudConcepts: 'Cloud Concepts',
    topicCloudTechnologyServices: 'Cloud Technology and Services',
    topicSecurityCompliance: 'Security and Compliance',
    practiceCountPrefix: 'Question',
    practiceCountMiddle: 'of',
    practiceCountSuffix: '',
    selectN: '{n} more needed',
    selectedNofN: 'Selected {n}/{total}',
    enToggle: 'EN',
    englishOriginal: 'English Original',
    close: 'Close',
    back: 'Back',
    notifications: 'Notifications',
    bookmark: 'Bookmark',
    loading: 'Loading',

    submit: 'Submit',
    skip: 'Skip',
    next: 'Next',
    retryAnswer: 'Retry',

    bannerCorrect: 'Correct',
    bannerWrong: 'Wrong',
    bannerPartial: 'Partial',
    correctAnswerIs: 'Correct answer is',
    yourAnswer: 'Your answer',
    explanationTitle: 'Explanation',
    explanationTag: 'AI · Markdown',
    voteTitle: 'Community votes',
    voteTitleMulti: 'Community answer combos',
    voteOptionCount: '{count} options',
    voteComboCount: '{count} combos',
    voteOther: 'Other',
    voteCorrect: 'Correct',
    voteYou: 'You',
    voteNotInDistribution: 'not in distribution',

    tabWrong: 'Wrong',
    tabBookmarks: 'Bookmarks',
    tabHome: 'Home',
    tabSettings: 'Settings',

    settingsAppearance: 'Appearance',
    settingsAccount: 'Account',
    accountSignedOutTitle: 'Sign in with GitHub',
    accountSignedOutDescription:
      'Signing in switches the app to account-local progress. Anonymous progress is not imported yet.',
    accountLocalProgressNotice: 'Anonymous progress stays local and is not imported yet.',
    signInWithGitHub: 'Sign in with GitHub',
    accountSignedIn: 'Signed in',
    accountGitHubUser: 'GitHub account',
    accountSyncStatus: 'Sync status',
    accountSyncCurrentCert: 'Certification sync enabled',
    accountSyncCurrentCertDescription: 'Your selected certification follows this GitHub account.',
    signOut: 'Sign out',
    signOutClearsProgress: 'Signing out clears the current account-local progress mirror.',
    loginWelcome: 'Welcome back',
    loginSubtitle: 'Sign in to sync progress across devices',
    loginOr: 'or',
    continueAsGuest: 'Continue as guest',
    guestModeNotice: 'Guest mode: progress is stored on this device only',
    loginAuthError: 'GitHub sign-in was not completed. Try again or continue as guest.',
    loginOnboardingError: 'Could not save this choice. Please try again.',
    loginAccountPreferencesError: 'Could not load your account preferences. Please try again.',
    loginLanguageToggle: 'Switch language',
    settingsTheme: 'Theme',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeSystem: 'System',
    settingsLanguage: 'Language',
    settingsLanguageLabel: 'Interface language',
    langZh: '中文',
    langEn: 'English',
    settingsAbout: 'About',
    settingsVersion: 'Version',
    settingsPrivacy: 'Privacy',
    settingsLicense: 'License',

    emptyWrong: 'No wrong answers — keep going ✨',
    wrongCountBadge: 'Wrong {count}x',
    emptyBookmarks: 'No bookmarks yet. Mark questions while practicing.',
    emptyAllAnswered: "You've answered everything ✨",
    emptyAllAnsweredCta: 'Review wrong answers',
    questionNotFound: 'Question not found',

    backToHome: 'Back to home',
    viewLastResult: 'View last result',
    practiceCompleteTitle: 'Practice complete',
    practiceCompleteDescription: 'There are no unanswered questions left for this certification.',
    wrongReviewCompleteTitle: 'Wrong-list review complete',
    wrongReviewCompleteDescription: 'You have reviewed every question in this wrong-list session.',
    bookmarksReviewCompleteTitle: 'Bookmark review complete',
    bookmarksReviewCompleteDescription:
      'You have reviewed every question in this bookmark session.',
    backToWrongList: 'Back to wrong list',
    backToBookmarks: 'Back to bookmarks',
    loadFailed: 'Failed to load',
    retry: 'Retry',
  },
} as const

export type StringKey = keyof typeof STRINGS.zh
