export const STRINGS = {
  zh: {
    appName: 'ace-aws',
    appTagline: 'AWS 认证刷题',
    greetingGuestName: '云端学徒',
    greetingMorning: '上午好，{name}',
    greetingAfternoon: '下午好，{name}',
    greetingEvening: '晚上好，{name}',
    greetingNight: '晚安，{name}',
    settingsTitle: '设置',
    selectCertTitle: '选择认证',
    selectCertSubtitle: '选择你正在备考的 AWS 认证',
    selectCertCta: '开始练习',
    selectCertSaveFailed: '无法保存选择，请重试。',
    questionListTitle: '题目列表',

    certDvaTitle: '开发人员',
    certDvaSelectTitle: '开发人员',
    certClfTitle: '云从业者',
    certAifTitle: 'AI 从业者',
    certSaaTitle: '解决方案架构师',
    certSoaTitle: 'SysOps 管理员',
    certDeaTitle: '数据工程师',
    certMlaTitle: '机器学习工程师',
    certSapTitle: '解决方案架构师',
    certDopTitle: 'DevOps 工程师',
    certAnsTitle: '高级网络',
    certScsTitle: '安全',
    certMlsTitle: '机器学习',
    certGroupFoundational: '基础级',
    certGroupAssociate: '助理级',
    certGroupProfessional: '专家级',
    certGroupSpecialty: '专项',
    certQuestions: '{count} 题',
    certComingSoon: '即将上线',
    certHot: 'HOT',
    certSwitchChip: '切换',
    certSwitchAria: '切换认证',
    certSwitchTitle: '切换认证',
    certSwitchSubtitle: '进度按认证分别保存',
    certSwitchCurrent: '当前认证',
    certSwitchOther: '其他认证',
    certSwitchBrowseAll: '查看全部认证',
    selectCertBrowseTitle: '全部认证',
    selectCertBrowseSubtitle: '查看全部 AWS 认证。CLF-C02、DVA-C02 与 SAA-C03 题库已就绪。',
    selectCertBrowseCta: '继续当前认证',

    homeContinue: '继续刷题',
    homeAnswered: '已答题',
    homeAccuracy: '正确率',
    homeWrongRedo: '错题重做',
    homeSmartPractice: '智能刷题',
    homeSmartPracticeDescription: '每次 10 题',
    homeSmartPracticeError: '暂时无法开始智能刷题，请重试。',
    homeList: '题目列表',
    homeBookmarks: '收藏',
    homeQuickStart: '快速开始',
    mockExam: '模拟考试',
    mockExamFullSimulation: '模拟真实考试环境',
    mockExamQuestions: '题',
    mockExamQuestionsShort: '题',
    mockExamMinutes: '分钟',
    mockExamPassScoreUnit: '及格分 /1000',
    mockExamBegin: '开始考试',
    mockExamStart: '开始',
    mockExamResume: '继续',
    mockExamPaused: '已暂停',
    mockExamTimeLeftShort: '剩余',
    mockExamTimeLeftSaved: '剩余时间已保存',
    mockExamAnsweredProgressAria: '模拟考试已答进度',
    mockExamExitTitle: '退出模拟考试？',
    mockExamExitSubtitle: '你可以保存剩余时间后返回首页，或继续留在考试中。',
    mockExamStayInExam: '留在考试中',
    mockExamSaveAndExit: '保存并退出',
    mockExamDiscardDraft: '丢弃草稿',
    mockExamDiscardTitle: '丢弃这份模拟考试草稿？',
    mockExamDiscardSubtitle: '此操作会删除本次模考的答案、标记和剩余时间，且无法撤销。',
    mockExamDiscardWarning: '此操作无法撤销。',
    mockExamKeepDraft: '返回',
    mockExamDiscardConfirm: '永久丢弃',
    mockExamRules: '考试规则',
    mockExamQuestionGrid: '答题卡',
    mockExamViewAnswerSheet: '查看答题卡',
    mockExamFlagged: '已标记',
    mockExamPrevious: '上一题',
    mockExamFlag: '标记',
    mockExamAnswered: '已答',
    mockExamUnanswered: '未答',
    mockExamSkipped: '未答',
    mockExamResumeExam: '继续答题',
    mockExamUnansweredWarning: '还有 {count} 道题未作答',
    mockExamSubmitTitle: '提交模拟考试？',
    mockExamSubmitSubtitle: '提交后结果会保存到模拟考试历史，不能再修改。',
    mockExamSubmitUnansweredWarning: '{count} 道未答题会计入扣分。',
    mockExamSubmitCancel: '返回检查',
    mockExamSubmitConfirm: '确认交卷',
    mockExamPassed: '通过',
    mockExamFailed: '未通过',
    mockExamOutOf1000: '满分 1000',
    mockExamPassScore: '通过分',
    mockExamCorrect: '正确',
    mockExamAccuracy: '正确率',
    mockExamTimeUsed: '用时',
    mockExamTimeLeft: '剩余时间',
    mockExamBreakdown: '领域分析',
    mockExamReviewAnswers: '回顾答案',
    mockExamFirstTimeTitle: '你的首次模考',
    mockExamFirstTimeDescription:
      '建议在不被打扰的 {minutes} 分钟内完成。完成后可查看分数趋势与逐题回顾。',
    mockExamRuleAllQuestionsScore: '全程限时，考试进行中计时器不会暂停。',
    mockExamRuleExplanationsHidden: '可标记题目以后回看，交卷后不可修改。',
    mockExamRuleUnansweredWrong: '考试过程中不显示题目解析。',
    mockExamRuleFlagQuestions: '到时未交卷将自动提交。',
    mockExamRuleSaveExit: '中途可保存并退出，保存进度与剩余时间。',
    mockExamStartError: '暂时无法开始模拟考试，请重试。',
    mockExamQuestionLoadError: '无法加载模拟考试题目，请重试。',
    mockExamHistoryLoadError: '无法加载考试记录，请重试。',
    mockExamAutoSubmittedToast: '时间已到，模拟考试已自动提交。',
    mockExamHistory: '考试记录',
    mockExamAttemptN: '第 {n} 次考试',
    mockExamAttemptsLabel: '{count} 次',
    mockExamLatest: '最近一次',
    mockExamAllAttempts: '全部记录',
    mockExamTimeout: '超时',
    mockExamBest: '最佳',
    mockExamAvg: '平均',
    mockExamPassRate: '通过率',
    mockExamScoreTrend: '分数趋势',
    mockExamReviewTitle: '逐题回顾',
    mockExamReviewAll: '全部',
    mockExamReviewWrong: '错题',
    mockExamReviewEmptyWrong: '本次考试没有错题。',
    mockExamReviewEmptyFlagged: '本次考试没有标记题。',
    mockExamAnswerSheet: '答题卡',
    mockExamBackToQuestion: '回到题目',
    mockExamYourAnswer: '你的回答',
    mockExamCorrectAnswer: '正确答案',
    mockExamNoAnswer: '未作答',
    mockExamDomainDevelopmentWithAwsServices: '使用 AWS 服务进行开发',
    mockExamDomainSecurity: '安全',
    mockExamDomainDeployment: '部署',
    mockExamDomainTroubleshootingOptimization: '故障排除与优化',
    mockExamDomainCloudConcepts: '云概念',
    mockExamDomainSecurityCompliance: '安全与合规',
    mockExamDomainCloudTechnologyServices: '云技术与服务',
    mockExamDomainBillingPricingSupport: '账单、定价与支持',
    mockExamDomainDesignSecureArchitectures: '设计安全架构',
    mockExamDomainDesignResilientArchitectures: '设计弹性架构',
    mockExamDomainDesignHighPerformingArchitectures: '设计高性能架构',
    mockExamDomainDesignCostOptimizedArchitectures: '设计成本优化架构',

    questionXofY: '第 {x} 题 / 共 {y} 题',
    badgeSingle: '单选',
    badgeMulti: '多选 · {n}',
    topicDeployment: '部署',
    topicDevelopment: '开发',
    topicSecurity: '安全',
    topicTroubleshooting: '故障排除',
    topicBillingPricingSupport: '账单、定价与支持',
    topicCloudConcepts: '云概念',
    topicCloudTechnologyServices: '云技术与服务',
    topicSecurityCompliance: '安全与合规',
    topicDesignSecureArchitectures: '设计安全架构',
    topicDesignResilientArchitectures: '设计弹性架构',
    topicDesignHighPerformingArchitectures: '设计高性能架构',
    topicDesignCostOptimizedArchitectures: '设计成本优化架构',
    practiceCountPrefix: '第',
    practiceCountMiddle: '题 / 共',
    practiceCountSuffix: '题',
    selectN: '还需选择 {n} 项',
    selectedNofN: '已选 {n}/{total}',
    enToggle: 'EN',
    englishOriginal: '英文原文',
    close: '关闭',
    back: '返回',
    notifications: '通知',
    bookmark: '收藏',
    loading: '加载中',

    submit: '提交',
    skip: '跳过',
    next: '下一题',

    bannerCorrect: '回答正确',
    bannerWrong: '回答错误',
    bannerPartial: '部分正确',
    questionStatusCorrect: '正确',
    questionStatusWrong: '错误',
    questionStatusUnanswered: '未答',
    correctAnswerIs: '正确答案是',
    yourAnswer: '你的回答',
    explanationTitle: '解析',
    explanationTag: 'AI · Markdown',
    voteTitle: '社区投票分布',
    voteTitleMulti: '社区作答组合',
    voteOptionCount: '{count} 项',
    voteComboCount: '{count} 种',
    voteOther: '其他',
    voteCorrect: '正确',
    voteYou: '你',
    voteNotInDistribution: '未在投票中',

    tabAll: '全部',
    tabWrong: '错过',
    tabBookmarks: '收藏',
    tabUnanswered: '未答',
    tabHome: '首页',
    tabSettings: '设置',

    settingsAppearance: '外观',
    settingsAccount: '账号',
    accountSignedOutDescription: '登录后可跨设备同步进度，并导入此浏览器的匿名进度。',
    signInWithGitHub: '使用 GitHub 登录',
    accountGitHubUser: 'GitHub 账号',
    accountProgressSyncStateSyncing: '正在同步',
    accountProgressSyncStateFailed: '同步失败',
    accountProgressSyncStateDirty: '有未同步进度',
    accountProgressSyncStateSynced: '已同步',
    accountProgressSyncLastSynced: '上次同步：{time}',
    accountProgressSyncNeverSynced: '尚未成功同步',
    accountProgressSyncManualSuccessToast: '进度已同步。',
    accountProgressSyncManualFailure: '暂时无法同步。你的进度仍保存在本机。',
    accountProgressSyncSignOutBlockedTitle: '退出前仍有未同步进度',
    accountProgressSyncSignOutBlockedDescription:
      '进度暂时无法同步。你可以重试同步，或仍然退出并清除此账号本地镜像。',
    accountProgressSyncRetrySync: '重试同步',
    accountProgressSyncStillSignOut: '仍然退出',
    accountProgressSyncSyncNow: '立即同步',
    accountProgressSyncTitle: '正在同步账号进度',
    accountProgressSyncDescription: '正在恢复 {cert} 的账号进度，请稍候。',
    accountProgressSyncErrorTitle: '账号进度同步失败',
    accountProgressSyncErrorDescription: '{cert} 的账号进度暂时无法恢复。你可以重试或退出登录。',
    accountProgressSyncPartialToast: '部分进度无法同步，已从账号恢复。',
    accountProgressSyncTemporaryToast: '进度暂时无法同步，将自动重试。',
    accountProgressSyncPayloadToast: '进度同步已暂停。本地进度仍保留。',
    accountProgressSyncUnknownCertToast: '该认证的进度同步已停止。',
    anonymousImportTitle: '导入匿名进度',
    anonymousImportDescription: '此浏览器保存了未登录时的练习进度。导入后会同步到当前账号。',
    anonymousImportSummary: '认证：{certCount} 个；进度记录：{recordCount} 条。',
    anonymousImportCta: '导入进度',
    anonymousImportSkip: '暂不导入',
    anonymousImportFailure: '暂时无法导入匿名进度。匿名进度仍保存在本机。',
    settingsAnonymousImportCta: '导入匿名进度',
    settingsAnonymousImportSuccessToast: '匿名进度已导入。',
    settingsAnonymousImportFailureToast: '暂时无法导入匿名进度。匿名进度仍保存在本机。',
    signOut: '退出登录',
    loginWelcome: '欢迎回来',
    loginSubtitle: '登录后同步进度到所有设备',
    loginOr: '或',
    continueAsGuest: '以游客身份继续',
    guestModeNotice: '游客模式：进度仅保存在本机',
    loginAuthError: 'GitHub 登录未完成，请重试或以游客身份继续。',
    loginOnboardingError: '无法保存选择，请重试。',
    loginAccountPreferencesError: '无法加载账号偏好，请重试。',
    loginSyncExpired: '同步会话已过期。请重新登录以继续同步。',
    loginLanguageToggle: '切换语言',
    settingsTheme: '主题',
    themeLight: '浅色',
    themeDark: '深色',
    themeSystem: '跟随系统',
    settingsLanguage: '语言',
    settingsLanguageLabel: '界面语言',
    langZh: '中文',
    langEn: 'English',
    settingsAbout: '关于',
    settingsVersion: '版本',
    settingsRepository: '项目仓库',
    settingsPrivacy: '隐私说明',
    settingsLicense: '开源协议',

    emptyWrong: '暂无错题，继续努力 ✨',
    wrongCountBadge: '错 {count} 次',
    emptyBookmarks: '还没收藏任何题目，去练习中标记吧',
    emptyAllAnswered: '已全部答完 ✨',
    emptyQuestionList: '暂无可用题目',
    questionNotFound: '题目不存在',

    backToHome: '返回首页',
    viewLastResult: '查看上次结果',
    practiceCompleteTitle: '练习完成',
    practiceCompleteDescription: '该认证已没有未作答题目。',
    allQuestionsReviewCompleteTitle: '全部题目复习完成',
    allQuestionsReviewCompleteDescription: '本轮全部题目已复习完成。',
    wrongReviewCompleteTitle: '错题复习完成',
    wrongReviewCompleteDescription: '本轮错题已全部复习完成。',
    bookmarksReviewCompleteTitle: '收藏复习完成',
    bookmarksReviewCompleteDescription: '本轮收藏题目已全部复习完成。',
    unansweredReviewCompleteTitle: '未答题练习完成',
    unansweredReviewCompleteDescription: '本轮未答题已全部完成。',
    wrongRedoCompleteTitle: '错题重做完成',
    wrongRedoCompleteDescription: '本轮错题重做已完成。',
    smartPracticeCompleteTitle: '本次完成！',
    smartPracticeCompleteDescription: '{count} 题',
    smartPracticeCompleteHeadline: '本轮答对 {correct} / {total} 题',
    smartPracticeRingLabel: '正确',
    smartPracticeAgain: '再来一轮',
    smartPracticeAgainPending: '正在开始...',
    smartPracticeStatAccuracy: '正确率',
    smartPracticeStatWrong: '错题数',
    smartPracticeStatRoundSize: '本轮题数',
    smartPracticeStatRoundUnit: '题',
    backToList: '返回列表',
    backToWrongList: '返回错题列表',
    backToBookmarks: '返回收藏',
    backToUnanswered: '返回未答',
    retry: '重试',
  },
  en: {
    appName: 'ace-aws',
    appTagline: 'AWS certification practice',
    greetingGuestName: 'CloudLearner',
    greetingMorning: 'Good morning, {name}',
    greetingAfternoon: 'Good afternoon, {name}',
    greetingEvening: 'Good evening, {name}',
    greetingNight: 'Good night, {name}',
    settingsTitle: 'Settings',
    selectCertTitle: 'Choose certification',
    selectCertSubtitle: 'Pick the AWS exam you are preparing for',
    selectCertCta: 'Start practicing',
    selectCertSaveFailed: 'Could not save your selection. Try again.',
    questionListTitle: 'Question list',

    certDvaTitle: 'Developer Associate',
    certDvaSelectTitle: 'Developer',
    certClfTitle: 'Cloud Practitioner',
    certAifTitle: 'AI Practitioner',
    certSaaTitle: 'Solutions Architect',
    certSoaTitle: 'SysOps Administrator',
    certDeaTitle: 'Data Engineer',
    certMlaTitle: 'Machine Learning',
    certSapTitle: 'Solutions Architect',
    certDopTitle: 'DevOps Engineer',
    certAnsTitle: 'Advanced Networking',
    certScsTitle: 'Security',
    certMlsTitle: 'Machine Learning',
    certGroupFoundational: 'Foundational',
    certGroupAssociate: 'Associate',
    certGroupProfessional: 'Professional',
    certGroupSpecialty: 'Specialty',
    certQuestions: '{count} questions',
    certComingSoon: 'Coming soon',
    certHot: 'HOT',
    certSwitchChip: 'Switch',
    certSwitchAria: 'Switch certification',
    certSwitchTitle: 'Switch certification',
    certSwitchSubtitle: 'Progress is tracked per certification',
    certSwitchCurrent: 'Current',
    certSwitchOther: 'Other certifications',
    certSwitchBrowseAll: 'Browse all certifications',
    selectCertBrowseTitle: 'All certifications',
    selectCertBrowseSubtitle:
      'Browse every AWS certification. CLF-C02, DVA-C02, and SAA-C03 banks are ready right now.',
    selectCertBrowseCta: 'Continue current certification',

    homeContinue: 'Continue',
    homeAnswered: 'Answered',
    homeAccuracy: 'Accuracy',
    homeWrongRedo: 'Wrong redo',
    homeSmartPractice: 'Smart practice',
    homeSmartPracticeDescription: '10 questions',
    homeSmartPracticeError: 'Could not start smart practice. Try again.',
    homeList: 'Question list',
    homeBookmarks: 'Bookmarks',
    homeQuickStart: 'Quick start',
    mockExam: 'Mock Exam',
    mockExamFullSimulation: 'Full real-exam simulation',
    mockExamQuestions: 'Questions',
    mockExamQuestionsShort: 'Qs',
    mockExamMinutes: 'min',
    mockExamPassScoreUnit: 'Pass score /1000',
    mockExamBegin: 'Begin exam',
    mockExamStart: 'Start',
    mockExamResume: 'Resume',
    mockExamPaused: 'Paused',
    mockExamTimeLeftShort: 'left',
    mockExamTimeLeftSaved: 'Time left saved',
    mockExamAnsweredProgressAria: 'Mock exam answered progress',
    mockExamExitTitle: 'Exit mock exam?',
    mockExamExitSubtitle: 'Save your remaining time before returning home, or stay in the exam.',
    mockExamStayInExam: 'Stay in exam',
    mockExamSaveAndExit: 'Save and exit',
    mockExamDiscardDraft: 'Discard draft',
    mockExamDiscardTitle: 'Discard this mock exam draft?',
    mockExamDiscardSubtitle:
      'This deletes answers, flags, and remaining time for this mock exam. It cannot be undone.',
    mockExamDiscardWarning: 'This action cannot be undone.',
    mockExamKeepDraft: 'Back',
    mockExamDiscardConfirm: 'Discard permanently',
    mockExamRules: 'Exam rules',
    mockExamQuestionGrid: 'Question grid',
    mockExamViewAnswerSheet: 'View answer sheet',
    mockExamFlagged: 'Flagged',
    mockExamPrevious: 'Prev',
    mockExamFlag: 'Flag',
    mockExamAnswered: 'Answered',
    mockExamUnanswered: 'Unanswered',
    mockExamSkipped: 'Skipped',
    mockExamResumeExam: 'Resume exam',
    mockExamUnansweredWarning: '{count} questions still unanswered',
    mockExamSubmitTitle: 'Submit mock exam?',
    mockExamSubmitSubtitle:
      'After submission, the result is saved to Mock Exam History and cannot be changed.',
    mockExamSubmitUnansweredWarning: '{count} unanswered questions will count against your score.',
    mockExamSubmitCancel: 'Back to review',
    mockExamSubmitConfirm: 'Submit exam',
    mockExamPassed: 'Passed',
    mockExamFailed: 'Failed',
    mockExamOutOf1000: 'out of 1000',
    mockExamPassScore: 'Pass score',
    mockExamCorrect: 'Correct',
    mockExamAccuracy: 'Accuracy',
    mockExamTimeUsed: 'Time used',
    mockExamTimeLeft: 'Time left',
    mockExamBreakdown: 'Domain breakdown',
    mockExamReviewAnswers: 'Review answers',
    mockExamFirstTimeTitle: 'Your first mock exam',
    mockExamFirstTimeDescription:
      'Plan an uninterrupted {minutes}-minute block. After finishing you will see score trends and per-question review.',
    mockExamRuleAllQuestionsScore: 'Timer runs continuously while the exam is in progress.',
    mockExamRuleExplanationsHidden: 'Flag questions to revisit; answers are final after submit.',
    mockExamRuleUnansweredWrong: 'Explanations are hidden during the exam.',
    mockExamRuleFlagQuestions: 'Auto-submit when time runs out.',
    mockExamRuleSaveExit: 'You can save and exit mid-exam; progress and remaining time are kept.',
    mockExamStartError: 'Could not start the mock exam. Try again.',
    mockExamQuestionLoadError: 'Could not load the mock exam question. Try again.',
    mockExamHistoryLoadError: 'Could not load exam history. Try again.',
    mockExamAutoSubmittedToast: 'Time expired. Your mock exam was submitted.',
    mockExamHistory: 'Exam history',
    mockExamAttemptN: 'Attempt #{n}',
    mockExamAttemptsLabel: '{count} attempts',
    mockExamLatest: 'latest',
    mockExamAllAttempts: 'All attempts',
    mockExamTimeout: 'Timeout',
    mockExamBest: 'Best',
    mockExamAvg: 'Avg',
    mockExamPassRate: 'Pass rate',
    mockExamScoreTrend: 'Score trend',
    mockExamReviewTitle: 'Review answers',
    mockExamReviewAll: 'All',
    mockExamReviewWrong: 'Wrong',
    mockExamReviewEmptyWrong: 'No wrong questions in this attempt.',
    mockExamReviewEmptyFlagged: 'No flagged questions in this attempt.',
    mockExamAnswerSheet: 'Answer sheet',
    mockExamBackToQuestion: 'Back to question',
    mockExamYourAnswer: 'Your answer',
    mockExamCorrectAnswer: 'Correct answer',
    mockExamNoAnswer: 'No answer',
    mockExamDomainDevelopmentWithAwsServices: 'Development with AWS Services',
    mockExamDomainSecurity: 'Security',
    mockExamDomainDeployment: 'Deployment',
    mockExamDomainTroubleshootingOptimization: 'Troubleshooting and Optimization',
    mockExamDomainCloudConcepts: 'Cloud Concepts',
    mockExamDomainSecurityCompliance: 'Security and Compliance',
    mockExamDomainCloudTechnologyServices: 'Cloud Technology and Services',
    mockExamDomainBillingPricingSupport: 'Billing, Pricing, and Support',
    mockExamDomainDesignSecureArchitectures: 'Design Secure Architectures',
    mockExamDomainDesignResilientArchitectures: 'Design Resilient Architectures',
    mockExamDomainDesignHighPerformingArchitectures: 'Design High-Performing Architectures',
    mockExamDomainDesignCostOptimizedArchitectures: 'Design Cost-Optimized Architectures',

    questionXofY: 'Question {x} of {y}',
    badgeSingle: 'Single',
    badgeMulti: 'Multi · {n}',
    topicDeployment: 'Deployment',
    topicDevelopment: 'Development',
    topicSecurity: 'Security',
    topicTroubleshooting: 'Troubleshooting',
    topicBillingPricingSupport: 'Billing, Pricing, and Support',
    topicCloudConcepts: 'Cloud Concepts',
    topicCloudTechnologyServices: 'Cloud Technology and Services',
    topicSecurityCompliance: 'Security and Compliance',
    topicDesignSecureArchitectures: 'Design Secure Architectures',
    topicDesignResilientArchitectures: 'Design Resilient Architectures',
    topicDesignHighPerformingArchitectures: 'Design High-Performing Architectures',
    topicDesignCostOptimizedArchitectures: 'Design Cost-Optimized Architectures',
    practiceCountPrefix: 'Question',
    practiceCountMiddle: 'of',
    practiceCountSuffix: '',
    selectN: '{n} more needed',
    selectedNofN: 'Selected {n}/{total}',
    enToggle: 'EN',
    englishOriginal: 'English Original',
    close: 'Close',
    back: 'Back',
    notifications: 'Notifications',
    bookmark: 'Bookmark',
    loading: 'Loading',

    submit: 'Submit',
    skip: 'Skip',
    next: 'Next',

    bannerCorrect: 'Correct',
    bannerWrong: 'Wrong',
    bannerPartial: 'Partial',
    questionStatusCorrect: 'Correct',
    questionStatusWrong: 'Wrong',
    questionStatusUnanswered: 'Unanswered',
    correctAnswerIs: 'Correct answer is',
    yourAnswer: 'Your answer',
    explanationTitle: 'Explanation',
    explanationTag: 'AI · Markdown',
    voteTitle: 'Community votes',
    voteTitleMulti: 'Community answer combos',
    voteOptionCount: '{count} options',
    voteComboCount: '{count} combos',
    voteOther: 'Other',
    voteCorrect: 'Correct',
    voteYou: 'You',
    voteNotInDistribution: 'not in distribution',

    tabAll: 'All',
    tabWrong: 'Wrong',
    tabBookmarks: 'Bookmarks',
    tabUnanswered: 'Unanswered',
    tabHome: 'Home',
    tabSettings: 'Settings',

    settingsAppearance: 'Appearance',
    settingsAccount: 'Account',
    accountSignedOutDescription:
      "Sign in to sync progress across devices and import this browser's Anonymous Progress.",
    signInWithGitHub: 'Sign in with GitHub',
    accountGitHubUser: 'GitHub account',
    accountProgressSyncStateSyncing: 'Syncing',
    accountProgressSyncStateFailed: 'Sync failed',
    accountProgressSyncStateDirty: 'Unsynced progress',
    accountProgressSyncStateSynced: 'Synced',
    accountProgressSyncLastSynced: 'Last synced: {time}',
    accountProgressSyncNeverSynced: 'Not synced yet',
    accountProgressSyncManualSuccessToast: 'Progress synced.',
    accountProgressSyncManualFailure: 'Sync is unavailable. Your progress is still saved here.',
    accountProgressSyncSignOutBlockedTitle: 'Unsynced progress remains',
    accountProgressSyncSignOutBlockedDescription:
      'Progress could not sync right now. Retry sync, or sign out anyway and clear this account-local mirror.',
    accountProgressSyncRetrySync: 'Retry sync',
    accountProgressSyncStillSignOut: 'Still sign out',
    accountProgressSyncSyncNow: 'Sync now',
    accountProgressSyncTitle: 'Syncing account progress',
    accountProgressSyncDescription: 'Restoring account progress for {cert}.',
    accountProgressSyncErrorTitle: 'Account progress could not sync',
    accountProgressSyncErrorDescription:
      'Account progress for {cert} could not be restored yet. Retry or sign out.',
    accountProgressSyncPartialToast:
      'Some progress could not sync and was restored from your account.',
    accountProgressSyncTemporaryToast: 'Progress sync is temporarily unavailable. Retrying soon.',
    accountProgressSyncPayloadToast: 'Progress sync paused. Local progress is still saved.',
    accountProgressSyncUnknownCertToast: 'Progress sync stopped for this certification.',
    anonymousImportTitle: 'Import Anonymous Progress',
    anonymousImportDescription:
      'This browser has practice progress from before you signed in. Import it to sync with this account.',
    anonymousImportSummary:
      'Certifications: {certCount}; progress records: {recordCount} on this browser.',
    anonymousImportCta: 'Import progress',
    anonymousImportSkip: 'Skip import',
    anonymousImportFailure:
      'Anonymous progress could not import right now. It is still saved here.',
    settingsAnonymousImportCta: 'Import anonymous progress',
    settingsAnonymousImportSuccessToast: 'Anonymous progress imported.',
    settingsAnonymousImportFailureToast:
      'Anonymous progress could not import right now. It is still saved here.',
    signOut: 'Sign out',
    loginWelcome: 'Welcome back',
    loginSubtitle: 'Sign in to sync progress across devices',
    loginOr: 'or',
    continueAsGuest: 'Continue as guest',
    guestModeNotice: 'Guest mode: progress is stored on this device only',
    loginAuthError: 'GitHub sign-in was not completed. Try again or continue as guest.',
    loginOnboardingError: 'Could not save this choice. Please try again.',
    loginAccountPreferencesError: 'Could not load your account preferences. Please try again.',
    loginSyncExpired: 'Your sync session expired. Sign in again to continue syncing.',
    loginLanguageToggle: 'Switch language',
    settingsTheme: 'Theme',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeSystem: 'System',
    settingsLanguage: 'Language',
    settingsLanguageLabel: 'Interface language',
    langZh: '中文',
    langEn: 'English',
    settingsAbout: 'About',
    settingsVersion: 'Version',
    settingsRepository: 'Project repository',
    settingsPrivacy: 'Privacy',
    settingsLicense: 'License',

    emptyWrong: 'No wrong answers — keep going ✨',
    wrongCountBadge: 'Wrong {count}x',
    emptyBookmarks: 'No bookmarks yet. Mark questions while practicing.',
    emptyAllAnswered: "You've answered everything ✨",
    emptyQuestionList: 'No questions available.',
    questionNotFound: 'Question not found',

    backToHome: 'Back to home',
    viewLastResult: 'View last result',
    practiceCompleteTitle: 'Practice complete',
    practiceCompleteDescription: 'There are no unanswered questions left for this certification.',
    allQuestionsReviewCompleteTitle: 'All-question review complete',
    allQuestionsReviewCompleteDescription: 'You have reviewed every question in this list session.',
    wrongReviewCompleteTitle: 'Wrong-list review complete',
    wrongReviewCompleteDescription: 'You have reviewed every question in this wrong-list session.',
    bookmarksReviewCompleteTitle: 'Bookmark review complete',
    bookmarksReviewCompleteDescription:
      'You have reviewed every question in this bookmark session.',
    unansweredReviewCompleteTitle: 'Unanswered session complete',
    unansweredReviewCompleteDescription: 'You have completed this unanswered-question session.',
    wrongRedoCompleteTitle: 'Wrong redo complete',
    wrongRedoCompleteDescription: 'You have completed this wrong redo session.',
    smartPracticeCompleteTitle: 'Session complete',
    smartPracticeCompleteDescription: '{count} questions',
    smartPracticeCompleteHeadline: 'You got {correct} of {total} correct',
    smartPracticeRingLabel: 'Correct',
    smartPracticeAgain: 'Again',
    smartPracticeAgainPending: 'Starting...',
    smartPracticeStatAccuracy: 'Accuracy',
    smartPracticeStatWrong: 'Wrong',
    smartPracticeStatRoundSize: 'Round size',
    smartPracticeStatRoundUnit: 'q',
    backToList: 'Back to list',
    backToWrongList: 'Back to wrong list',
    backToBookmarks: 'Back to bookmarks',
    backToUnanswered: 'Back to unanswered',
    retry: 'Retry',
  },
} as const

export type StringKey = keyof typeof STRINGS.zh
