export const STRINGS = {
  zh: {
    appName: 'ace-aws',
    greeting: '上午好，云端学徒',
    settingsTitle: '设置',
    selectCertTitle: '选择认证',
    selectCertCta: '开始练习',
    questionListTitle: '题目列表',

    certDvaEyebrow: 'DVA-C02 · 助理工程师',
    certDvaTitle: 'Developer Associate',
    certDvaQCount: '557 题 · 热门',

    homeContinue: '继续练习',
    homeAnswered: '已答题',
    homeAccuracy: '正确率',
    homeWrong: '错题',
    homeBookmarks: '收藏',

    questionXofY: '第 {x} 题 / 共 {y} 题',
    badgeSingle: 'SINGLE',
    badgeMulti: 'MULTI · {n}',
    selectN: '还需选择 {n} 项',
    selectedNofN: '已选 {n}/{total}',
    enToggle: 'EN',
    englishOriginal: '英文原文',

    submit: '提交',
    skip: '跳过',
    next: '下一题',

    bannerCorrect: '回答正确',
    bannerWrong: '回答错误',
    bannerPartial: '部分正确',
    explanationTitle: '解析 · Explanation',
    voteTitle: '社区投票分布',

    tabWrong: '错题',
    tabBookmarks: '收藏',
    tabHome: '首页',
    tabSettings: '设置',

    settingsAppearance: '外观',
    settingsTheme: '主题',
    themeLight: '浅色',
    themeDark: '深色',
    themeSystem: '跟随系统',
    settingsLanguage: '语言',
    settingsLanguageLabel: '界面语言',
    langZh: '中文',
    langEn: 'English',
    settingsAbout: '关于',
    settingsVersion: '版本',
    settingsPrivacy: '隐私',
    settingsLicense: '开源协议',

    emptyWrong: '暂无错题，继续努力 ✨',
    emptyBookmarks: '还没收藏任何题目，去练习中标记吧',
    emptyAllAnswered: '已全部答完 ✨',
    emptyAllAnsweredCta: '去看错题',
    questionNotFound: '题目不存在',

    backToHome: '返回首页',
    loadFailed: '加载失败',
    retry: '重试',
  },
  en: {
    appName: 'ace-aws',
    greeting: 'Good morning, CloudLearner',
    settingsTitle: 'Settings',
    selectCertTitle: 'Choose certification',
    selectCertCta: 'Start practicing',
    questionListTitle: 'Question list',

    certDvaEyebrow: 'DVA-C02 · Associate',
    certDvaTitle: 'Developer Associate',
    certDvaQCount: '557 Q · HOT',

    homeContinue: 'Continue',
    homeAnswered: 'Answered',
    homeAccuracy: 'Accuracy',
    homeWrong: 'Wrong',
    homeBookmarks: 'Bookmarks',

    questionXofY: 'Question {x} of {y}',
    badgeSingle: 'SINGLE',
    badgeMulti: 'MULTI · {n}',
    selectN: '{n} more answer needed',
    selectedNofN: 'Selected {n}/{total}',
    enToggle: 'EN',
    englishOriginal: 'ENGLISH ORIGINAL',

    submit: 'Submit',
    skip: 'Skip',
    next: 'Next',

    bannerCorrect: 'Correct',
    bannerWrong: 'Wrong',
    bannerPartial: 'Partial',
    explanationTitle: 'Explanation',
    voteTitle: 'Community votes',

    tabWrong: 'Wrong',
    tabBookmarks: 'Bookmarks',
    tabHome: 'Home',
    tabSettings: 'Settings',

    settingsAppearance: 'Appearance',
    settingsTheme: 'Theme',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeSystem: 'System',
    settingsLanguage: 'Language',
    settingsLanguageLabel: 'Interface language',
    langZh: '中文',
    langEn: 'English',
    settingsAbout: 'About',
    settingsVersion: 'Version',
    settingsPrivacy: 'Privacy',
    settingsLicense: 'License',

    emptyWrong: 'No wrong answers — keep going ✨',
    emptyBookmarks: 'No bookmarks yet. Mark questions while practicing.',
    emptyAllAnswered: "You've answered everything ✨",
    emptyAllAnsweredCta: 'Review wrong answers',
    questionNotFound: 'Question not found',

    backToHome: 'Back to home',
    loadFailed: 'Failed to load',
    retry: 'Retry',
  },
} as const

export type StringKey = keyof typeof STRINGS.zh
